[book]
authors = ["hinto.janai"]
language = "en"
multilingual = false
src = "src"
title = "Festival"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/hinto-janai/festival"
